---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian_stretch_empty_vars
    image: debian:stretch
  - name: ubuntu_xenial_empty_vars
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: no_vars
  test_sequence:
    - lint
    - syntax
    - create
    - prepare
    - converge
verifier:
  name: testinfra
  lint:
    name: flake8
